// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaBox.Storage.Databases;

namespace PizzaBox.Storage.Migrations
{
    [DbContext(typeof(PizzaBoxDbContext))]
    partial class PizzaBoxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PizzaBox.Domain.Models.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("OrderId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            OrderId = 1L,
                            Date = new DateTime(2019, 11, 1, 7, 9, 14, 0, DateTimeKind.Unspecified),
                            StoreId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            OrderId = 2L,
                            Date = new DateTime(2019, 11, 17, 7, 9, 14, 0, DateTimeKind.Unspecified),
                            StoreId = 2L,
                            UserId = 2L
                        },
                        new
                        {
                            OrderId = 3L,
                            Date = new DateTime(2019, 12, 5, 7, 9, 14, 0, DateTimeKind.Unspecified),
                            StoreId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            OrderId = 4L,
                            Date = new DateTime(2019, 12, 6, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 1L,
                            UserId = 7L
                        },
                        new
                        {
                            OrderId = 5L,
                            Date = new DateTime(2019, 12, 31, 15, 9, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 2L,
                            UserId = 2L
                        },
                        new
                        {
                            OrderId = 6L,
                            Date = new DateTime(2020, 1, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 6L,
                            UserId = 9L
                        },
                        new
                        {
                            OrderId = 7L,
                            Date = new DateTime(2020, 2, 24, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 5L,
                            UserId = 10L
                        },
                        new
                        {
                            OrderId = 8L,
                            Date = new DateTime(2020, 3, 1, 14, 25, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 4L,
                            UserId = 1L
                        },
                        new
                        {
                            OrderId = 9L,
                            Date = new DateTime(2020, 3, 19, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            StoreId = 3L,
                            UserId = 8L
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.OrderPizza", b =>
                {
                    b.Property<long>("OrderPizzaId")
                        .HasColumnType("bigint");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("PizzaId")
                        .HasColumnType("bigint");

                    b.HasKey("OrderPizzaId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaId");

                    b.ToTable("OrderPizza");

                    b.HasData(
                        new
                        {
                            OrderPizzaId = 1L,
                            Amount = 2,
                            OrderId = 1L,
                            PizzaId = 3L
                        },
                        new
                        {
                            OrderPizzaId = 2L,
                            Amount = 3,
                            OrderId = 1L,
                            PizzaId = 5L
                        },
                        new
                        {
                            OrderPizzaId = 3L,
                            Amount = 1,
                            OrderId = 2L,
                            PizzaId = 2L
                        },
                        new
                        {
                            OrderPizzaId = 4L,
                            Amount = 1,
                            OrderId = 3L,
                            PizzaId = 4L
                        },
                        new
                        {
                            OrderPizzaId = 5L,
                            Amount = 2,
                            OrderId = 4L,
                            PizzaId = 6L
                        },
                        new
                        {
                            OrderPizzaId = 6L,
                            Amount = 1,
                            OrderId = 5L,
                            PizzaId = 2L
                        },
                        new
                        {
                            OrderPizzaId = 7L,
                            Amount = 3,
                            OrderId = 6L,
                            PizzaId = 7L
                        },
                        new
                        {
                            OrderPizzaId = 8L,
                            Amount = 1,
                            OrderId = 6L,
                            PizzaId = 8L
                        },
                        new
                        {
                            OrderPizzaId = 9L,
                            Amount = 7,
                            OrderId = 7L,
                            PizzaId = 9L
                        },
                        new
                        {
                            OrderPizzaId = 10L,
                            Amount = 2,
                            OrderId = 7L,
                            PizzaId = 6L
                        },
                        new
                        {
                            OrderPizzaId = 11L,
                            Amount = 3,
                            OrderId = 8L,
                            PizzaId = 5L
                        },
                        new
                        {
                            OrderPizzaId = 12L,
                            Amount = 1,
                            OrderId = 8L,
                            PizzaId = 1L
                        },
                        new
                        {
                            OrderPizzaId = 13L,
                            Amount = 2,
                            OrderId = 9L,
                            PizzaId = 9L
                        },
                        new
                        {
                            OrderPizzaId = 14L,
                            Amount = 1,
                            OrderId = 9L,
                            PizzaId = 7L
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Pizza", b =>
                {
                    b.Property<long>("PizzaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PizzaId");

                    b.ToTable("Pizza");

                    b.HasData(
                        new
                        {
                            PizzaId = 1L,
                            Description = "thin crust, tomato sauce, vegan cheese, pineapple, green pepper, onions",
                            Name = "SMALL HAWAIIAN PIZZA",
                            Price = 5.00m
                        },
                        new
                        {
                            PizzaId = 2L,
                            Description = "thin crust, tomato sauce, vegan cheese, pineapple, green pepper, onions",
                            Name = "MEDIUM HAWAIIAN PIZZA",
                            Price = 9.50m
                        },
                        new
                        {
                            PizzaId = 3L,
                            Description = "thin crust, tomato sauce, vegan cheese, pineapple, green pepper, onions",
                            Name = "LARGE HAWAIIAN PIZZA",
                            Price = 13.90m
                        },
                        new
                        {
                            PizzaId = 4L,
                            Description = "flatbread, tomato sauce, vegan cheese, tomatos, avocado, tofu, onions",
                            Name = "SMALL EXQUISITE PIZZA",
                            Price = 6.00m
                        },
                        new
                        {
                            PizzaId = 5L,
                            Description = "flatbread, tomato sauce, vegan cheese, tomatos, avocado, tofu, onions",
                            Name = "MEDIUM EXQUISITE PIZZA",
                            Price = 11.00m
                        },
                        new
                        {
                            PizzaId = 6L,
                            Description = "flatbread, tomato sauce, vegan cheese, tomatos, avocado, tofu, onions",
                            Name = "LARGE EXQUISITE PIZZA",
                            Price = 15.50m
                        },
                        new
                        {
                            PizzaId = 7L,
                            Description = "thick crust, pesto sauce, vegan cheese, onions, red pepper, mushrooms",
                            Name = "SMALL DELICIOUS PIZZA",
                            Price = 5.50m
                        },
                        new
                        {
                            PizzaId = 8L,
                            Description = "thick crust, pesto sauce, vegan cheese, onions, red pepper, mushrooms",
                            Name = "MEDIUM DELICIOUS PIZZA",
                            Price = 10.50m
                        },
                        new
                        {
                            PizzaId = 9L,
                            Description = "thick crust, pesto sauce, vegan cheese, onions, red pepper, mushrooms",
                            Name = "LARGE DELICIOUS PIZZA",
                            Price = 16.50m
                        },
                        new
                        {
                            PizzaId = 10L,
                            Description = "thick crust, tomato sauce, tomate, pineapple, avocado",
                            Name = "GIANT SUPER PIZZA",
                            Price = 59.90m
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Store", b =>
                {
                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StoreId");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            StoreId = 1L,
                            Address = "Cooper 786",
                            Name = "PizzaEater",
                            Password = "eater"
                        },
                        new
                        {
                            StoreId = 2L,
                            Address = "Mitchel 83",
                            Name = "DiegoPizza",
                            Password = "diego"
                        },
                        new
                        {
                            StoreId = 3L,
                            Address = "Mesquite 476",
                            Name = "MiPizza",
                            Password = "pizza"
                        },
                        new
                        {
                            StoreId = 4L,
                            Address = "Abram 34",
                            Name = "TuPizza",
                            Password = "pizza"
                        },
                        new
                        {
                            StoreId = 5L,
                            Address = "Cooper 132",
                            Name = "Mangiata",
                            Password = "comer"
                        },
                        new
                        {
                            StoreId = 6L,
                            Address = "Mesquite 87",
                            Name = "PizzaLover",
                            Password = "pizza"
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.StorePizza", b =>
                {
                    b.Property<long>("StorePizzaId")
                        .HasColumnType("bigint");

                    b.Property<int>("Inventory")
                        .HasColumnType("int");

                    b.Property<long>("PizzaId")
                        .HasColumnType("bigint");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.HasKey("StorePizzaId");

                    b.HasIndex("PizzaId");

                    b.HasIndex("StoreId");

                    b.ToTable("StorePizza");

                    b.HasData(
                        new
                        {
                            StorePizzaId = 1L,
                            Inventory = 2,
                            PizzaId = 1L,
                            StoreId = 1L
                        },
                        new
                        {
                            StorePizzaId = 2L,
                            Inventory = 2,
                            PizzaId = 2L,
                            StoreId = 1L
                        },
                        new
                        {
                            StorePizzaId = 3L,
                            Inventory = 2,
                            PizzaId = 3L,
                            StoreId = 1L
                        },
                        new
                        {
                            StorePizzaId = 4L,
                            Inventory = 2,
                            PizzaId = 4L,
                            StoreId = 1L
                        },
                        new
                        {
                            StorePizzaId = 5L,
                            Inventory = 2,
                            PizzaId = 5L,
                            StoreId = 1L
                        },
                        new
                        {
                            StorePizzaId = 6L,
                            Inventory = 2,
                            PizzaId = 6L,
                            StoreId = 1L
                        },
                        new
                        {
                            StorePizzaId = 7L,
                            Inventory = 2,
                            PizzaId = 7L,
                            StoreId = 1L
                        },
                        new
                        {
                            StorePizzaId = 8L,
                            Inventory = 2,
                            PizzaId = 8L,
                            StoreId = 1L
                        },
                        new
                        {
                            StorePizzaId = 9L,
                            Inventory = 2,
                            PizzaId = 9L,
                            StoreId = 1L
                        },
                        new
                        {
                            StorePizzaId = 10L,
                            Inventory = 2,
                            PizzaId = 10L,
                            StoreId = 1L
                        },
                        new
                        {
                            StorePizzaId = 11L,
                            Inventory = 2,
                            PizzaId = 1L,
                            StoreId = 2L
                        },
                        new
                        {
                            StorePizzaId = 12L,
                            Inventory = 2,
                            PizzaId = 2L,
                            StoreId = 2L
                        },
                        new
                        {
                            StorePizzaId = 13L,
                            Inventory = 2,
                            PizzaId = 3L,
                            StoreId = 2L
                        },
                        new
                        {
                            StorePizzaId = 14L,
                            Inventory = 2,
                            PizzaId = 4L,
                            StoreId = 2L
                        },
                        new
                        {
                            StorePizzaId = 15L,
                            Inventory = 2,
                            PizzaId = 5L,
                            StoreId = 2L
                        },
                        new
                        {
                            StorePizzaId = 16L,
                            Inventory = 2,
                            PizzaId = 6L,
                            StoreId = 2L
                        },
                        new
                        {
                            StorePizzaId = 17L,
                            Inventory = 2,
                            PizzaId = 7L,
                            StoreId = 2L
                        },
                        new
                        {
                            StorePizzaId = 18L,
                            Inventory = 2,
                            PizzaId = 8L,
                            StoreId = 2L
                        },
                        new
                        {
                            StorePizzaId = 19L,
                            Inventory = 2,
                            PizzaId = 9L,
                            StoreId = 2L
                        },
                        new
                        {
                            StorePizzaId = 20L,
                            Inventory = 2,
                            PizzaId = 10L,
                            StoreId = 2L
                        },
                        new
                        {
                            StorePizzaId = 21L,
                            Inventory = 2,
                            PizzaId = 1L,
                            StoreId = 3L
                        },
                        new
                        {
                            StorePizzaId = 22L,
                            Inventory = 2,
                            PizzaId = 2L,
                            StoreId = 3L
                        },
                        new
                        {
                            StorePizzaId = 23L,
                            Inventory = 2,
                            PizzaId = 3L,
                            StoreId = 3L
                        },
                        new
                        {
                            StorePizzaId = 24L,
                            Inventory = 2,
                            PizzaId = 4L,
                            StoreId = 3L
                        },
                        new
                        {
                            StorePizzaId = 25L,
                            Inventory = 2,
                            PizzaId = 5L,
                            StoreId = 3L
                        },
                        new
                        {
                            StorePizzaId = 26L,
                            Inventory = 2,
                            PizzaId = 6L,
                            StoreId = 3L
                        },
                        new
                        {
                            StorePizzaId = 27L,
                            Inventory = 2,
                            PizzaId = 7L,
                            StoreId = 3L
                        },
                        new
                        {
                            StorePizzaId = 28L,
                            Inventory = 2,
                            PizzaId = 8L,
                            StoreId = 3L
                        },
                        new
                        {
                            StorePizzaId = 29L,
                            Inventory = 2,
                            PizzaId = 9L,
                            StoreId = 3L
                        },
                        new
                        {
                            StorePizzaId = 30L,
                            Inventory = 2,
                            PizzaId = 10L,
                            StoreId = 3L
                        },
                        new
                        {
                            StorePizzaId = 31L,
                            Inventory = 2,
                            PizzaId = 1L,
                            StoreId = 4L
                        },
                        new
                        {
                            StorePizzaId = 32L,
                            Inventory = 2,
                            PizzaId = 2L,
                            StoreId = 4L
                        },
                        new
                        {
                            StorePizzaId = 33L,
                            Inventory = 2,
                            PizzaId = 3L,
                            StoreId = 4L
                        },
                        new
                        {
                            StorePizzaId = 34L,
                            Inventory = 2,
                            PizzaId = 4L,
                            StoreId = 4L
                        },
                        new
                        {
                            StorePizzaId = 35L,
                            Inventory = 2,
                            PizzaId = 5L,
                            StoreId = 4L
                        },
                        new
                        {
                            StorePizzaId = 36L,
                            Inventory = 2,
                            PizzaId = 6L,
                            StoreId = 4L
                        },
                        new
                        {
                            StorePizzaId = 37L,
                            Inventory = 2,
                            PizzaId = 7L,
                            StoreId = 4L
                        },
                        new
                        {
                            StorePizzaId = 38L,
                            Inventory = 2,
                            PizzaId = 8L,
                            StoreId = 4L
                        },
                        new
                        {
                            StorePizzaId = 39L,
                            Inventory = 2,
                            PizzaId = 9L,
                            StoreId = 4L
                        },
                        new
                        {
                            StorePizzaId = 40L,
                            Inventory = 2,
                            PizzaId = 10L,
                            StoreId = 4L
                        },
                        new
                        {
                            StorePizzaId = 41L,
                            Inventory = 2,
                            PizzaId = 1L,
                            StoreId = 5L
                        },
                        new
                        {
                            StorePizzaId = 42L,
                            Inventory = 2,
                            PizzaId = 2L,
                            StoreId = 5L
                        },
                        new
                        {
                            StorePizzaId = 43L,
                            Inventory = 2,
                            PizzaId = 3L,
                            StoreId = 5L
                        },
                        new
                        {
                            StorePizzaId = 44L,
                            Inventory = 2,
                            PizzaId = 4L,
                            StoreId = 5L
                        },
                        new
                        {
                            StorePizzaId = 45L,
                            Inventory = 2,
                            PizzaId = 5L,
                            StoreId = 5L
                        },
                        new
                        {
                            StorePizzaId = 46L,
                            Inventory = 2,
                            PizzaId = 6L,
                            StoreId = 5L
                        },
                        new
                        {
                            StorePizzaId = 47L,
                            Inventory = 2,
                            PizzaId = 7L,
                            StoreId = 5L
                        },
                        new
                        {
                            StorePizzaId = 48L,
                            Inventory = 2,
                            PizzaId = 8L,
                            StoreId = 5L
                        },
                        new
                        {
                            StorePizzaId = 49L,
                            Inventory = 2,
                            PizzaId = 9L,
                            StoreId = 5L
                        },
                        new
                        {
                            StorePizzaId = 50L,
                            Inventory = 2,
                            PizzaId = 10L,
                            StoreId = 5L
                        },
                        new
                        {
                            StorePizzaId = 51L,
                            Inventory = 2,
                            PizzaId = 1L,
                            StoreId = 6L
                        },
                        new
                        {
                            StorePizzaId = 52L,
                            Inventory = 2,
                            PizzaId = 2L,
                            StoreId = 6L
                        },
                        new
                        {
                            StorePizzaId = 53L,
                            Inventory = 2,
                            PizzaId = 3L,
                            StoreId = 6L
                        },
                        new
                        {
                            StorePizzaId = 54L,
                            Inventory = 2,
                            PizzaId = 4L,
                            StoreId = 6L
                        },
                        new
                        {
                            StorePizzaId = 55L,
                            Inventory = 2,
                            PizzaId = 5L,
                            StoreId = 6L
                        },
                        new
                        {
                            StorePizzaId = 56L,
                            Inventory = 2,
                            PizzaId = 6L,
                            StoreId = 6L
                        },
                        new
                        {
                            StorePizzaId = 57L,
                            Inventory = 2,
                            PizzaId = 7L,
                            StoreId = 6L
                        },
                        new
                        {
                            StorePizzaId = 58L,
                            Inventory = 2,
                            PizzaId = 8L,
                            StoreId = 6L
                        },
                        new
                        {
                            StorePizzaId = 59L,
                            Inventory = 2,
                            PizzaId = 9L,
                            StoreId = 6L
                        },
                        new
                        {
                            StorePizzaId = 60L,
                            Inventory = 2,
                            PizzaId = 10L,
                            StoreId = 6L
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            Address = "Central 960",
                            Name = "Bianca",
                            Password = "bianca"
                        },
                        new
                        {
                            UserId = 2L,
                            Address = "Street 4250",
                            Name = "Silvana",
                            Password = "silvana"
                        },
                        new
                        {
                            UserId = 3L,
                            Address = "Calle 13",
                            Name = "Macarena",
                            Password = "maca"
                        },
                        new
                        {
                            UserId = 4L,
                            Address = "3 Poniente",
                            Name = "Victoria",
                            Password = "vicky"
                        },
                        new
                        {
                            UserId = 5L,
                            Address = "Avenida Beio 15",
                            Name = "Rufuz",
                            Password = "beio"
                        },
                        new
                        {
                            UserId = 6L,
                            Address = "15 Norte",
                            Name = "NancyCastro",
                            Password = "nancy"
                        },
                        new
                        {
                            UserId = 7L,
                            Address = "Avenida Beio 15",
                            Name = "Jenny",
                            Password = "jenny"
                        },
                        new
                        {
                            UserId = 8L,
                            Address = "Blanca Estela 76",
                            Name = "Fernanda",
                            Password = "ferna"
                        },
                        new
                        {
                            UserId = 9L,
                            Address = "Los Pellines 950",
                            Name = "Francisca",
                            Password = "fran"
                        },
                        new
                        {
                            UserId = 10L,
                            Address = "Lomas de Montenar 1190",
                            Name = "Sofia",
                            Password = "sofia"
                        });
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.Order", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaBox.Domain.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.OrderPizza", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.Order", "Order")
                        .WithMany("OrderPizzas")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaBox.Domain.Models.Pizza", "Pizza")
                        .WithMany("OrderPizzas")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaBox.Domain.Models.StorePizza", b =>
                {
                    b.HasOne("PizzaBox.Domain.Models.Pizza", "Pizza")
                        .WithMany("StorePizzas")
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaBox.Domain.Models.Store", "Store")
                        .WithMany("StorePizzas")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
